fix(`git`): Use Global Hooks

diff --git a/files/git/hooks/pre-commit b/files/git/hooks/pre-commit
--- a/files/git/hooks/pre-commit
+++ b/files/git/hooks/pre-commit
@@ -3,7 +3,9 @@ error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }
 
 ## Pre-Commit Checks ##
 # Syntax
+nixos format ./.
+
 if [ "$(git branch --show-current)" == "stable" ]
 then
-  nixos check || error "Invalid Syntax"
+  nixos check ./. || error "Invalid Syntax"
 fi
