feat: Refine Scripts
Changes:
- Use `nix-shell` Shebangs
- Add `lib.build.script`
- Patch `git` Hooks
- Fix CI & Formatting

diff --git a/files/git/hooks/pre-commit b/files/git/hooks/pre-commit
--- a/files/git/hooks/pre-commit
+++ b/files/git/hooks/pre-commit
@@ -2,10 +2,8 @@
 error() { echo -e "\033[0;31merror:\033[0m $1"; exit 7; }
 
 ## Pre-Commit Checks ##
-# Syntax
-nixos format ./.
-
-if [ "$(git branch --show-current)" == "stable" ]
+# Nix Syntax
+if [ "$(find . -name '*.nix' 2>/dev/null | wc -l)" != 0 ] && [ "$(git branch --show-current)" == "stable" ]
 then
-  nixos check ./. || error "Invalid Syntax"
+  nix flake check || error "Invalid Syntax"
 fi
